#!/bin/bash

rm -f *.djs *.fdf *.ljs *.djs *.fdf *.aux *.log *.out *.qsl *.sol *.brf *.log *.toc 
rm -f article.pdf *.dvi
pdflatex article.tex &&
pdflatex article.tex &&
pdflatex article.tex &&
rm -f *.djs *.fdf *.ljs *.djs *.fdf *.aux *.out *.qsl *.sol *.cut *.brf *.log *.toc *.atfi
